# !/bin/bash

#EXEMPLE
A=3
B=$((100 * $A + 5)) # 305

#EXERCICE
COST_PINEAPPLE=50
COST_BANANA=4
COST_WATERMELON=23
COST_BASKET=1
TOTAL=$(( (1 * $COST_PINEAPPLE) + (2 * $COST_BANANA) + (3 * $COST_WATERMELON) + (1 * $COST_BASKET) ))
echo "Total Cost is $TOTAL"
